#!/usr/bin/env python3
"""
Generate the preview pages.

The chrome (unofficial ribbon, brand bar, the Y's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "finder":  "4yDZ3OFsq5WkNdhi2zmxUw",   # both pools, one day, a row per part of each pool; Teams menu
    "week":    "zgwZ3RYlPRRanWwEYspZW9",   # one campus, the whole week; Facilities menu (opens on North)
    "lap":     "Glpoiwy4qOzsSJ8ZCKLmLy",   # lap swim plus the high school blocks that close the pool
    "lessons": "489jlY8AAwllA22oMASAF6",   # group lessons (South Campus)
    "fit":     "fvAsyrx66tGkwVEipfhdDB",   # water fitness at both campuses
    "team":    "vXIZ5FQsUvOq8W5lUJJfrV",   # Y swim teams and high school swim & dive
}

NAV = [
    ("index.html",         "Find a swim time"),
    ("week.html",          "The pool week"),
    ("lap-swim.html",      "Lap Swim"),
    ("swim-lessons.html",  "Swim Lessons"),
    ("water-fitness.html", "Water Fitness"),
    ("swim-team.html",     "Swim Team"),
]

SITE = "https://ymcacollier.org"


def cal(key, title, cls="", caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="cal {cls}">
    <iframe width="100%" height="640" src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a YMCA of Collier County website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a YMCA of Collier County page. A mockup of an aquatics section for
  <a href="{SITE}/" target="_blank" rel="noopener">ymcacollier.org</a> with live
  <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">YMCA OF COLLIER COUNTY</span>Aquatics</a>
    <div class="tel">North Campus, Naples &middot; South Campus, Marco Island</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li><a href="{SITE}/membership.html" target="_blank" rel="noopener">Membership</a></li>
    <li><a href="{SITE}/schedules.html" target="_blank" rel="noopener">Schedules</a></li>
    <li class="on"><a href="index.html">Swimming</a></li>
    <li><a href="{SITE}/hours.html" target="_blank" rel="noopener">Hours</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what one aquatics schedule for both YMCA of
    Collier County pools could look like. Not affiliated with the YMCA of Collier County.</p>
    <p>Read on 25 September 2026 from the Y's <a href="{SITE}/schedules.html" target="_blank" rel="noopener">schedule</a>
    (the Pool filter), the <a href="{SITE}/hours.html" target="_blank" rel="noopener">Hours</a> page, the
    <a href="{SITE}/swimlessons.html" target="_blank" rel="noopener">swim lesson</a> and
    <a href="{SITE}/swimteam.html" target="_blank" rel="noopener">swim team</a> pages, and program registration.
    Calendars by <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics team</h2>
  <p>Everything on these calendars comes from what the Y publishes. These are the places where two of
  its own pages disagree, where a schedule isn't published, or where we had to make a call.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag clash">Conflict</span>North Campus: lap swim until 7:30pm?</div>
      <div class="a">The Hours page gives North Campus lap swim Monday&ndash;Thursday 5:30am&ndash;7:30pm.
      The schedule closes the pool 3&ndash;6pm Monday, Wednesday and Friday for high school swim &amp; dive
      practice, and 3&ndash;9pm Tuesday and Thursday for high school meets. The calendar follows the
      schedule.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>South Campus: two lanes, or the whole pool?</div>
      <div class="a">The Hours page says South Campus lap swim is 7am&ndash;3:30pm, then 4:30&ndash;6pm on
      &ldquo;2 lanes only&rdquo;, with swim team 3:30&ndash;6pm. The schedule lists Open Lap Swim
      7am&ndash;6pm with no break. The calendar follows the Hours page, because it names the lanes.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>When does the high school season end?</div>
      <div class="a">The practices and the Tuesday and Thursday meets are listed as repeating every week
      with no end date. Say when the season ends, and lap swim comes back on the calendar that evening.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>North Campus swim lessons</div>
      <div class="a">The swim lessons page says group lessons run at North Campus and South Campus.
      Registration lists fall sessions only at Marco Island.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Team and clinic times</div>
      <div class="a">The Competitive Swim Team, stroke clinics, synchronized swimming and Splash Ball have
      pages but no published times. The Youth Swim Team's weekday 3:30&ndash;6pm comes from the Hours page.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Lap lanes, program area and team lanes</div>
      <div class="a">Neither campus says which lanes lap swim keeps while classes, lessons and teams are in
      the water. We split each pool into a lap lane area and a program area, plus team lanes at South
      Campus, so the calendar can show them side by side.</div>
    </li>
  </ul>
</section>

"""


HUB = f"""<section class="wrap hero">
  <div class="crumb">Programs &raquo; Swimming</div>
  <h1>Find a swim time at the Y</h1>
  <p class="kicker">North Campus &middot; South Campus &middot; one calendar</p>
  <p class="lead">Both YMCA of Collier County pools on one calendar, one row for each part of each pool:
  the lap lanes, the program area where classes and lessons run, and the team lanes. Pick a
  <strong>day</strong>, and use the <strong>Teams</strong> menu to show one program.</p>

{cal("finder", "YMCA of Collier County — both pools, one day", "short",
     caption="Gray blocks are high school swim &amp; dive: the pool is closed to open swim.")}

  <div class="try">
    <div><b>Laps before work?</b>North Campus opens lap swim at 5:30am every weekday; South Campus at 7am.</div>
    <div><b>Laps after work on a Tuesday?</b>Only South Campus, until 6pm on two lanes. North Campus is
    closed for high school meets from 3pm.</div>
    <div><b>Lessons for a four-year-old?</b>Saturdays at Marco Island, 10:30am&ndash;noon, and weekday
    Safety Around Water classes.</div>
  </div>
</section>

<div class="trail">
  <div class="wrap">
    <h2>Where is the pool schedule?</h2>
    <p class="q">&ldquo;Can I swim laps at North Campus at 5pm on Tuesday?&rdquo;</p>
    <p>The Hours page says yes: lap swim until 7:30pm. The Open Swim page says to &ldquo;check pool
    schedules&rdquo; and links to a class schedule that has no pool times in it. The pool times are on
    the Schedules page, under the heading &ldquo;Group Fitness Schedule&rdquo;, one day at a time, once
    you tick <i>Pool</i> &mdash; and there the answer is no: the pool is reserved for a high school swim
    meet from 3 to 9pm.</p>
    <p class="answer">On this calendar the answer is the same everywhere, because <b>every page reads the
    same schedule</b>. When the high school season ends, the staff change it once in an AI chat, and lap
    swim is back on the Hours, Swimming and Schedules pages that evening.</p>
  </div>
</div>

<section class="wrap">
  <h2>By program</h2>
  <div class="cards">
    <a class="card" href="week.html"><div class="pic loc"></div><div class="body">
      <h3>The pool week</h3><p>One campus, Sunday to Saturday, everything in the water.</p></div></a>
    <a class="card" href="lap-swim.html"><div class="pic lap"></div><div class="body">
      <h3>Lap Swim</h3><p>Lap swim at both campuses, and the blocks that close the pool.</p></div></a>
    <a class="card" href="swim-lessons.html"><div class="pic les"></div><div class="body">
      <h3>Swim Lessons</h3><p>Fall group lessons and Safety Around Water, by age.</p></div></a>
    <a class="card" href="water-fitness.html"><div class="pic fit"></div><div class="body">
      <h3>Water Fitness</h3><p>18 classes a week: aqua aerobics, Aqua Zumba, Aqua Fit and more.</p></div></a>
    <a class="card" href="swim-team.html"><div class="pic team"></div><div class="body">
      <h3>Swim Team</h3><p>Novice and Youth Swim Team, and high school swim &amp; dive.</p></div></a>
  </div>
</section>

{QUESTIONS}"""


WEEK = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; The pool week</div>
  <h1>The pool week</h1>
  <p class="kicker">Pick a campus from the Facilities menu</p>
  <p class="lead">Everything in one campus's pool, Sunday to Saturday: lap swim, water fitness, lessons,
  team practice and the high school blocks. It opens on North Campus in Naples; switch to South Campus
  (Marco Island) or <strong>All</strong>.</p>

{cal("week", "YMCA of Collier County — the pool week", "tall")}
</section>

<section class="wrap">
  <h2>The campuses</h2>
  <div class="facts">
    <div><b>North Campus</b>5450 YMCA Road, Naples, FL 34109. Pool open for lap swim from 5:30am
    weekdays, 6:30am Saturday, 8am Sunday.</div>
    <div><b>South Campus</b>101 Sand Hill Street, Marco Island, FL 34145. Lap swim from 7am weekdays,
    8am on weekends.</div>
  </div>
</section>

"""


LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">Both campuses &middot; included with membership</p>
  <p class="lead">Open lap swim at North Campus and South Campus, with the high school swim &amp; dive
  blocks that close the North Campus pool shown in gray. Use the <strong>Facilities</strong> menu to show
  one campus.</p>

{cal("lap", "YMCA of Collier County — lap swim", "tall")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The evening that isn't there</h2>
    <p>The Hours page lists North Campus lap swim until 7:30pm Monday through Thursday. On Tuesday and
    Thursday, the pool schedule has a high school swim meet from 3 to 9pm, and on Monday, Wednesday and
    Friday high school practice from 3 to 6pm.</p>
    <p class="answer">Here the evening gap is <b>on the calendar</b>, so a swimmer sees it before driving
    over, and South Campus's two open lanes show up as the place to go instead.</p>
  </div>
</div>

"""


LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Swim Lessons</div>
  <h1>Group Swim Lessons</h1>
  <p class="kicker">Fall sessions &middot; South Campus, Marco Island</p>
  <p class="lead">Parent &amp; Tot for ages 2 and under, Intermediate for ages 3&ndash;5 and
  Beginner/Intermediate for ages 6 and up on Saturdays through November 7, plus grant-funded Safety Around
  Water classes on weekdays. Tap a class for its dates.</p>

{cal("lessons", "YMCA of Collier County — swim lessons")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Every session, in one week</h2>
    <p>Today the sessions are in a registration search: eight cards, each with a date range, days and a
    time, one after another.</p>
    <p class="answer">On a week, a parent sees at a glance that <b>Saturday morning runs 10:30 to 12:30,
    one age group after another</b>, and that the weekday classes fall at 9:30 and after 2pm.</p>
  </div>
</div>

"""


FIT = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Water Fitness</div>
  <h1>Water Fitness</h1>
  <p class="kicker">18 classes a week &middot; both campuses</p>
  <p class="lead">Shallow and deep water aqua aerobics and Aqua Zumba at North Campus; Aqua Fit, Aqua
  Jogging, Aqua Step and Aqua Zumba at South Campus. Use the <strong>Facilities</strong> menu to show one
  campus.</p>

{cal("fit", "YMCA of Collier County — water fitness")}
</section>

"""


TEAM = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Swim Team</div>
  <h1>Swim Team</h1>
  <p class="kicker">Ages 6&ndash;17 &middot; both campuses</p>
  <p class="lead">The Novice Swim Team practices Monday and Wednesday evenings at North Campus, and the
  Youth Swim Team weekday afternoons at South Campus. High school swim &amp; dive has the North Campus
  pool on weekday afternoons.</p>

{cal("team", "YMCA of Collier County — swim team")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Four programs without a time</h2>
    <p>The Competitive Swim Team, stroke clinics, synchronized swimming and Splash Ball each have a page
    and a registration link, but no practice times anywhere on the site.</p>
    <p class="answer">Entered once, each shows up here and on the pool week, <b>beside the lap lanes it
    shares the water with</b>.</p>
  </div>
</div>

"""


PAGES = [
    ("index.html", "Swimming at the Y — YMCA of Collier County (preview)",
     "Both YMCA of Collier County pools on one live calendar.", HUB),
    ("week.html", "The pool week — YMCA of Collier County (preview)",
     "Everything in one campus's pool for the week.", WEEK),
    ("lap-swim.html", "Lap Swim — YMCA of Collier County (preview)",
     "Lap swim at North Campus and South Campus.", LAP),
    ("swim-lessons.html", "Swim Lessons — YMCA of Collier County (preview)",
     "Fall group swim lessons by age.", LESSONS),
    ("water-fitness.html", "Water Fitness — YMCA of Collier County (preview)",
     "Water fitness classes at both campuses.", FIT),
    ("swim-team.html", "Swim Team — YMCA of Collier County (preview)",
     "Swim team practice and high school swim and dive.", TEAM),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        with open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(shell(slug, title, description, body))
        print("wrote", slug)
